### ISSUE TITLE
First prompt renders improperly

### ISSUE THREAD

**Issue by rupansh** [IlanCosman/tide#124]
#### Describe the bug

The first prompt is malformed when terminal(tested kitty/alacritty) is launched.
Sometimes the first prompt doesn't render at all even.
The right most character is clipping but its happening in alacritty only. (This behavior doesn't happen with p10k though).

#### Steps to reproduce

1. Use bspwm (may or may not happen on other tiling wms)
2. Start terminal
3. First prompt doesn't render properly

#### Expected behavior

First prompt should render properly

#### Screenshots

https://user-images.githubusercontent.com/3929608/111072551-15139b00-8501-11eb-9a8e-467eacbc8f27.mp4

https://user-images.githubusercontent.com/3929608/111072677-9ff49580-8501-11eb-9b16-ecd2e61bdf9b.mp4

#### Environment (please complete the following information)

- Operating System: Arch Linux 5.11.1-arch1-1
- Output of `tide bug-report`: 

```console
fish, version 3.2.0
tide, version 4.2.0
alacritty
```

**Comment by IlanCosman** [comment]
Thanks for submitting this bug report 😄 I have a feeling this might be related to https://github.com/IlanCosman/tide/issues/109, so I'll wait for Fish 3.2.1 to track this down.

**Comment by rupansh** [comment]
can confirm the issue doesn't exist in
```console
fish, version 3.1.2
tide, version 4.1.1
alacritty
```

**Comment by vergenzt** [comment]
I decided today to switch to `fish` and I encountered this after a fresh install of the latest versions of`fish` (v3.2.0) and `tide` (v4.2.0). I also have been encountering some other issue that seems like the vim mode indicator wasn't updating? 🤔 Not sure. Either way, given https://github.com/IlanCosman/tide/issues/124#issuecomment-798941735 I decided to downgrade until a fix is released. I was able to follow the instructions at fish-shell/fish-shell#5497 to downgrade to `fish` 3.1.2 and `tide` 4.1.1 (using Homebrew/homebrew-core@d22625eb2e4aee75d45b55c39664cb711297d6e6).

(Note I had to temporarily switch my default shell to `/bin/bash` in order to `/usr/local/bin/brew install fish` after rolling back -- I had just uninstalled `fish` so it no longer worked! 😬)

**Comment by IlanCosman** [comment]
@vergenzt Thanks for pointing out that vi mode was bugged. The recent switch to using the `fish_prompt` event handler broke it. I don't really want to revert the change because the `fish_prompt` event is much more elegant, but I'll see if I can adapt to fix vi mode.

**Comment by IlanCosman** [comment]
@vergenzt There, vi mode is usable now, still a small bug tho.

**Comment by IlanCosman** [comment]
Closing because I believe this has been solved.

**Comment by rupansh** [comment]
![image](https://user-images.githubusercontent.com/3929608/113063568-27652880-91d3-11eb-81ea-c9e1eba4006f.png)
The right most character is still clipping on alacritty
This behavior didn't happen on 1.4.1
Is there a way to confirm whether this issue is tide related or fish related?

**Comment by rupansh** [comment]
> The first prompt being the wrong width will happen because Fish/your terminal doesn't set the correct column value early enough.
> 
> As for the slightly cut off character, honestly that seem wm or terminal related. The character is obviously being printed, so I don't think it can be related to Tide.

I see
