### ISSUE TITLE
Unexpected ellipsis in long path

### ISSUE THREAD

**Issue by peng1999** [IlanCosman/tide#131]
#### Describe the bug

Sometimes unexpected ellipsis are shown in the beginning of the pwd prompt, hiding pwd characters.

#### Steps to reproduce

1. Set terminal width to 50 columns.
2.
   ```sh
   mkdir -p /tmp/very/veryvery/very/very/very/very/long/path/abc/very/veryvery/
   cd /tmp/very/veryvery/very/very/very/very/long/path/abc/very/veryvery/
   ```
3. `…mp/v/v/v/v/v/v/l/path/abc/very/veryvery` is shown
4. This happens sometimes with path containing wide character:
    <img width="535" alt="image" src="https://user-images.githubusercontent.com/12483662/111865314-57c1f100-89a1-11eb-8fc6-3f034c3ab9f7.png">

#### Expected behavior

`/tmp/v/v/v/v/v/v/l/p/abc/very/veryvery` is shown.

#### Screenshots

<img width="521" alt="2021-03-20_17-12" src="https://user-images.githubusercontent.com/12483662/111865261-f568f080-89a0-11eb-847e-baa982dfb281.png">

#### Environment (please complete the following information)

- Operating System: Manjaro Linux
- Output of `tide bug-report`: 
```
fish, version 3.2.1-3-gc2eef7c25
tide, version 4.2.0
alacritty
```

**Comment by IlanCosman** [comment]
I can't reproduce this on Arch or MacOS, but lets keep it open and see if anyone else has this problem. Thanks for reporting 👍

**Comment by tomvdsom** [comment]
With a fresh (empty) `~/.config/fish`, installing fisher and subsequenty Tide, any too long pathname results in a prefix-ellipsis and the too long path chopped of instead of path-parts truncating (if not ambiguous) as mentioned in the readme.

`…unabriviated/very/very/very/long/path/parts/here branch-name !1 ❯`

`tide bug-report` output:

fish, version 3.2.1
tide, version 4.3.1
xterm-256color

On Mac, with the iTerm2 terminal emulator.  Fish started from bash (i.s.o. default shell) as `fish`.

**Comment by IlanCosman** [comment]
Alright, yeah, I can reproduce this. Unfortunately I can't really prevent this bug.

Basically the problem is that the `pwd` item doesn't know how short to truncate itself. Currently it's super dumb, you just give it a number `tide_pwd_truncate_margin`, and it will try to not go past that. Obviously this fails if you have a right prompt, or other left prompt items, that are longer than the margin.

Each side of the prompt runs separately, so I could make the right prompt run first, and then have `pwd` adapt to the right prompt's length. However, if there are other left prompt items, the ellipses will appear again. I can't figure out how long the left prompt would be without `pwd`.

So yeah, thanks for the report 😄 I'll solve the right prompt issue at least, but this bug will never fully go away. It would probably involve a complete restructuring of the project, and come at a moderate speed penalty 😞

**Comment by IlanCosman** [comment]
@romkatv How does p10k solve this problem? If segments are run serially, how does pwd know how short to make itself? Or does p10k do something fancier (I imagine so 😄)?

**Comment by romkatv** [comment]
> does p10k do something fancier

Yes. It special-cases `dir`.
