### ISSUE TITLE
Tide doesn't start on launch

### ISSUE THREAD

**Issue by 2ndemosthenes** [IlanCosman/tide#136]
I've always used powerlevel10k and today started to try fish and after I installed Tide, sometimes when I start the terminal, I have to input something to make Tide to show up, otherwise it's stuck like this:
![fish-tide](https://user-images.githubusercontent.com/46780868/113038002-37691200-91ab-11eb-90da-708460f08318.png)
So is it supposed to act this way, or something's broken?

**Comment by IlanCosman** [comment]
Please use the bug report template in the future. What OS are you running? What's the output of `tide bug-report`?

**Comment by 2ndemosthenes** [comment]
Sorry!
I'm on openSUSE Tumbleweed, here's the output:
```
❯ tide bug-report
fish, version 3.2.0
tide, version 4.3.2
xterm-256color
```

**Comment by IlanCosman** [comment]
No worries 😄 It's really important though because Tide is on the cutting edge of what Fish can do, so we often find bugs in Fish itself. You're running Fish 3.2.0, which has such a bug. I think this is the same issue as  https://github.com/IlanCosman/tide/issues/109. You should upgrade your Fish version to 3.2.1, that should solve this.
