### ISSUE TITLE
Is there a way to shorten the prompt ?

### ISSUE THREAD

**Issue by aniketgm** [IlanCosman/tide#167]
Sometimes the prompt grows big if there are files way inside in some folder.
As suggested in the README, I tried to shorten the prompt by doing

`$ set tide_left_prompt_items (basename pwd)`

But it doesn't seem to work.

![wycp7bQ871](https://user-images.githubusercontent.com/14215698/123556085-f632cf00-d7a6-11eb-9a0f-2b390a7f6894.gif)

**Comment by IlanCosman** [comment]
> As suggested in the README, I tried to shorten the prompt by doing
> $ set tide_left_prompt_items (basename pwd)

Ah, I can see how that would be misunderstood. 

That doesn't work because what we're doing is calling `_tide_item_$var` for each element in `tide_left_prompt_items`. So there's a function called `_tide_item_pwd`, and that's what's getting called when you have `pwd` in your `tide_left_prompt_items`.

> Is there a way to shorten the prompt?

In v4, set `tide_pwd_truncate_margin` to a large number. That will shorted every directory to one lettter, except the last.

In v5, which I'll release in probably a few weeks, you'll set `tide_prompt_min_cols` to the minimum number of columns you want.

**Comment by lumbo7332** [comment]
Hi, I'm still confused about how this works. I've set `tide_prompt_min_cols` to both high and low numbers, and it doesn't seem to truncate differently.

**Comment by IlanCosman** [comment]
> if using one-line prompt, Tide attempts to have at least this many columns for you to type in

My apologies if you already read that, but does it help? If you're using a two-line prompt, Tide will shorten the prompt as appropriate, user has no control. If using a one-line prompt, Tide will try to leave `tide_prompt_min_cols` columns for you to type in.

**Comment by lumbo7332** [comment]
I'm using a one-line prompt.
