### ISSUE TITLE
newline after time

### ISSUE THREAD

**Issue by ironfish** [IlanCosman/tide#169]
How do I set a `newline` on the right prompt after the `time` item? 

- I've tried but it pushes `time` to the next line on the right prompt. For example `tide_right_prompt_items status cmd_duration context jobs nvm virtual_env rust php vi_mode newline chruby` 
- Also in `tide_right_prompt_items status cmd_duration context jobs nvm virtual_env rust php vi_mode chruby` I don't see time listed.

**Comment by IlanCosman** [comment]
If I'm understanding this correctly, you are editing files that come with Tide. Those files are used for Tide's configuration wizard, so you shouldn't touch them. That's why you don't see the `time` item, because it isn't there by default. One of the steps in the wizard asks if you want to add it.

If you want to customize after the wizard, you should run commands either from the CLI or in your `config.fish`. For example, to add a `newline` to the end of `tide_right_prompt_items`, you would run `set --append tide_right_prompt_items newline`. Or if you wanted full control you would do `set tide_right_prompt_items item1 item2 newline item3 item4`.

**Comment by ironfish** [comment]
Okay, does that mean one never mods the tide files under `fish/functions/tide/configure/configs/'? If so, then when you want to add items to the `left or right` prompt,  it's done either by `CLI` or editing `config.fish`?

**Comment by IlanCosman** [comment]
Yes, exactly.

**Comment by ironfish** [comment]
Okay, thanks for the explanation.

**Comment by IlanCosman** [comment]
Oh, woops, one small mistake: You should never append or prepend to universal variables in `config.fish`. In general I'd reccomend just doing your configuration from the CLI, or from an script that you run once. You should probably only have a few things to configure anyways.

**Comment by ironfish** [comment]
`universal variables` meaning `tide` variables like `chruby` or `php` etc. correct? Also, I'm assuming you store some sort of config after running the configuration wizard. Where is that stored?

Just for clarity, I'm adding `java version` and `Scala version` variables. If I can get them to work, maybe I will do a PR.

**Comment by ironfish** [comment]
okay, using the `CLI` I got the results I wanted.

<img width="1895" alt="Screen Shot 2021-07-06 at 5 12 12 PM" src="https://user-images.githubusercontent.com/1911792/124667395-57c8fc80-de7d-11eb-9fff-bd6b9bbc0b33.png">

**Comment by IlanCosman** [comment]
Great 😄
