### ISSUE TITLE
Configuring tide without calling `tide configure`

### ISSUE THREAD

**Issue by fivegrant** [IlanCosman/tide#17]
I'm using [Home-Manager](https://github.com/rycee/home-manager) on [NixOS](https://github.com/NixOS/nixpkgs) and since everything has to be declared ahead of time, I was wondering if that can be done with Tide. I'm assuming if I canconfigure before running fish I can avoid this error (apologize about the ugly nix store names):

```
[five@desktop:~/home-configuration]$ fish
/nix/store/xvin9f4plkmd5bgmclhis1jz2swj6xny-source/functions/_tide_git_prompt_set_vars.fish (line 2): switch: Expected exactly one argument, got 0

    switch $tide_git_prompt_bg_color
           ^
in function “_tide_git_prompt_set_vars”
	called on line 3 of file /nix/store/xvin9f4plkmd5bgmclhis1jz2swj6xny-source/conf.d/_tide_Ω_init.fish

from sourcing file /nix/store/xvin9f4plkmd5bgmclhis1jz2swj6xny-source/conf.d/_tide_Ω_init.fish
	called on line 15 of file ~/.config/fish/conf.d/plugin-tide.fish

from sourcing file ~/.config/fish/conf.d/plugin-tide.fish
	called on line 305 of file /nix/store/aq7sz6wvcwc5wpbwyy8rxwi8c7clkalb-fish-3.0.2/share/fish/config.fish

from sourcing file /nix/store/aq7sz6wvcwc5wpbwyy8rxwi8c7clkalb-fish-3.0.2/share/fish/config.fish
	called during startup

string replace: Expected argument
math: Expected at least 1 args, got only 0
string replace: Expected argument
```

I'm new to fish so I might need to change something in the fish config file as well.

**Comment by IlanCosman** [comment]
Hmm, I'm afraid I might not be much help to you, this is a very out of the norm use case that I'm not familiar with. Thanks for asking though 😄 

Do universal variables still work with your setup? I.e if you run `set -U foo hello`, will it stick around for the next time you open the prompt? If universal variables work, Tide should as well.

**Comment by fivegrant** [comment]
I can set universal variables. Could I just set all the options I want for tide using them?

**Comment by IlanCosman** [comment]
Tide should do that automatically on install or after finishing `tide configure`...

**Comment by IlanCosman** [comment]
I assume you've tried finishing `tide configure`?

**Comment by fivegrant** [comment]
Yah, it doesn't work. Any tide command I run will return an error with additional errors on startup. By design, NixOS doesn't install anything outside of `/nix/store` which is really tripping things up right now. Usually, I can make this kind of thing work,  but I'm going using nix-built Home-Manager which acts as the package manager for fish. The file locations only seem to fail `tide configure` though and not tide on startup

**Comment by IlanCosman** [comment]
Hmm, so what happens to `~/.config/fish`? Do you have one? Where do your functions, conf.d snippets etc. go?

**Comment by fivegrant** [comment]
Sorry, I explained poorly. `~/.config/fish` exists. I can still install to my home directory. I mean everything that's usually in `/usr/bin` or somewhere similar goes into `/nix/store/` with a sha256 appended to the beginning of the name

**Comment by fivegrant** [comment]
home-manager, made links for some of the files in fish. The config options are there but the installation of the actual program is in `nix-store`.
```
~/home-configuration:ls /nix/store//xvin9f4plkmd5bgmclhis1jz2swj6xny-source/
CODE_OF_CONDUCT.md  completions/  conf.d/  CONTRIBUTING.md  functions/  LICENSE.md  README.md  tide_theme/  tools/
```

**Comment by IlanCosman** [comment]
If `~/.config/fish` is persistent then there's no reason for Tide to be having issues 😕 Maybe try uninstalling and reinstalling? Generic advice i know sorry.

Also could you run `echo $__fish_config_dir` for me and `echo $_tide_dir`? Thanks.

**Comment by IlanCosman** [comment]
Maybe Tide is freaking out not knowing where the `tide_theme` directory is. Can you run `echo $_tide_dir` for me, and also check if there is a symlink at `~/.config/fish/tide_theme`?

**Comment by fivegrant** [comment]
```
~/home-configuration:ls ~/.config/fish/
conf.d/  config.fish@  fish_variables  functions/
~/home-configuration:cd conf.d
cd: The directory “conf.d” does not exist
~/home-configuration:ls ~/.config/fish/conf.d/
plugin-tide.fish@
~/home-configuration:echo $__fish_config_dir
/home/five/.config/fish
~/home-configuration:echo $_tide_dir

~/home-configuration:ls ~/.config/fish/
conf.d/  config.fish@  fish_variables  functions/
~/home-configuration:ls ~/.config/fish/conf.d/
plugin-tide.fish@
~/home-configuration:ls ~/.config/fish/functions/
fish_greeting.fish@  fish_prompt.fish@
~/home-configuration:echo $_tide_git_dir 
/home/five/home-configuration
~/home-configuration:
```

**Comment by IlanCosman** [comment]
Did you install Tide through the `tide_install` function?

**Comment by IlanCosman** [comment]
`curl -sL git.io/tide | source && tide_install` is currently the only supported install method. Tide has a bit of a strange file structure because I didn't want to dump all of the files in `tide_theme` into the usual functions directory. It seems like you didn't install it this way, and that's probably why you're experiencing issues.

**Comment by fivegrant** [comment]
Yah, I didn't install it that way, and I can't use the `tide_install` because it works against the structure of the os I'm using. My PM relies on ingesting something that's usually handled by fisher or oh-my-fish

**Comment by fivegrant** [comment]
Could I fork this repo and move all of the contents of `tide_theme`? Could it be ingested by traditional package managers then?

**Comment by IlanCosman** [comment]
Ahh ok yeah that explains it. I definitely should have asked earlier but in the future it would be useful to put that in the original issue. I don't have other installation methods listed in the readme because they don't work. I'm looking forward to adding fisher support soon though after [this issue](https://github.com/jorgebucaran/fisher/issues/581) clears up and fisher 4.0 is released.

Moving the contents of `tide_theme` wont work. There's lots of other things the install script does as well like setting variables. Hopefully fisher 4.0 will be out soon and you can enjoy Tide the way you'd like 😄.

**Comment by fivegrant** [comment]
Thanks for your help

**Comment by NickHu** [comment]
I too am running into this, after having installed tide with [home-manager](https://github.com/nix-community/home-manager). This allows for fish plugins to be configured like so https://rycee.gitlab.io/home-manager/options.html#opt-programs.fish.plugins.

The way this is implemented is that each repository for each fish plugin gets its own path in the read-only nix store, e.g. for tide:

```sh
~ ❯ ls /nix/store/bm67a1b7nyh64z2w5hswi5ylviq6wrl0-source
CHANGELOG.md  CODE_OF_CONDUCT.md  completions  conf.d  CONTRIBUTING.md  docs  functions  LICENSE.md  README.md  resources
```

Then a file `plugin-PLUGINNAMEHERE.fish` file is installed to `~/.config/fish/conf.d` with the contents:

```fish
# Plugin tide
set -l plugin_dir /nix/store/bm67a1b7nyh64z2w5hswi5ylviq6wrl0-source

# Set paths to import plugin components
if test -d $plugin_dir/functions
  set fish_function_path $fish_function_path[1] $plugin_dir/functions $fish_function_path[2..-1]
end

if test -d $plugin_dir/completions
  set fish_complete_path $fish_complete_path[1] $plugin_dir/completions $fish_complete_path[2..-1]
end

# Source initialization code if it exists.
if test -d $plugin_dir/conf.d
  for f in $plugin_dir/conf.d/*.fish
    source $f
  end
end

if test -f $plugin_dir/key_bindings.fish
  source $plugin_dir/key_bindings.fish
end

if test -f $plugin_dir/init.fish
  source $plugin_dir/init.fish
end
```

(This is implemented [here](https://github.com/nix-community/home-manager/blob/ef72617c4a1e14ddb2254b2199bd0103c6274bf5/modules/programs/fish.nix#L428-L456))

Effectively, you get a read-only clone of the plugin in the nix store, and then the above fish snippet to chainload the plugin when you use fish. Tide does not work this way because it requires some kind of local state; when it's installed it writes a bunch of stuff to `fish_variables`.

Would it be possible to support this usecase?

**Comment by IlanCosman** [comment]
Hi Nick. I don't appreciate you calling Tide "buggy" when you're installing through an unsupported method that operates differently from the usual fish rules. It is probably possible to support your usecase using a large file containing global-variables, but it wouldn't be easy and I'm not interested in doing so.

**Comment by NickHu** [comment]
That comment was regarding some orthogonal issues I am having when installing Tide through Fisher 4.0 as the README suggests; it seems to not update the current working directory reliably when changing directory, and doesn't seem to interact with dircolors well. If you'd like, I can open a separate issue. I didn't mean to be disparaging at all.

**Comment by IlanCosman** [comment]
Got it, It wasn't clear to me that you were having unrelated issues, my apologies. I'd very much appreciate you opening a separate issue.

**Comment by IlanCosman** [comment]
Sorry you're having issues Nick. I don't currently have enough information to diagnose the problem. I don't know what you mean by dircolors. Please open a separate issue if you'd like to get it fixed.
