### ISSUE TITLE
Pure prompt does not show git dirty state

### ISSUE THREAD

**Issue by Debilski** [IlanCosman/tide#18]
I look at `funced _tide_item_git_prompt` and see that it calls `fish_git_prompt` (in `share/fish/functions/fish_git_prompt.fish`), which tells me:

```
# In addition, if you set __fish_git_prompt_showdirtystate to a nonempty value,
# unstaged (*) and staged (+) changes will be shown next to the branch name.
# You can configure this per-repository with the bash.showDirtyState variable,
# which defaults to true once __fish_git_prompt_showdirtystate is enabled. The
# choice to leave the variable as 'bash' instead of renaming to 'fish' is done
# to preserve compatibility with existing configured repositories.
```

I have set both 

    set __fish_git_prompt_showdirtystate 1
    set __bash_git_prompt_showdirtystate 1

But dirty files are still not marked with a `*` when I’m in a git repo. What’s the trick to enable this?

**Comment by IlanCosman** [comment]
Thanks for reporting this. This is in fact a "bug" though not in the code.

I was misled when creating the Pure style because [Pure](https://github.com/rafaelrinaldi/pure) does a strange thing in that it indicates either the staged state or dirty state with a single \* character:

```fish
~/clownfish master
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

~/clownfish master
❯ touch blah.rs # Doesn't effect prompt

~/clownfish master
❯ git add blah.rs # Stages a file, activating * in prompt

~/clownfish master*
❯ git restore --staged blah.rs # Unstaged file, removes * in prompt

~/clownfish master
❯ echo foo >> README.md # Makes a file dirty, thus producing a * in prompt

~/clownfish master*
❯ git add blah.rs # Stages blah.rs, but doesn't activate a second *

~/clownfish master*
❯
```

`fish_git_prompt` won't let you do this because it separates the staged and dirty states. Pure style will now indicate both states with the \* character, but there will be 2 \*s when both are true.

**Comment by Debilski** [comment]
Thanks for the quick fix. This is much better as a default. As I still enjoy the distinction between `*` and `+`, I guess, I’ll have to add a

    set __fish_git_prompt_char_stagedstate +

to my config then.
