### ISSUE TITLE
NO git status logo

### ISSUE THREAD

**Issue by Ahanaf-Ether** [IlanCosman/tide#226]
I love this prompt, but the thing that annoys me is i can get icons working but then when i "cd" into a git file it doesnt show the nice git branch icon, now i know i can change it in the config file, but should it be default for "many icons" option while configuring the prompt. Thanks!

**Comment by IlanCosman** [comment]
> it doesnt show the nice git branch icon

Which icon are you referring to?

**Comment by Ahanaf-Ether** [comment]
Master branch icon

**Comment by IlanCosman** [comment]
Could you copy-paste it here, or take a screenshot?

**Comment by Ahanaf-Ether** [comment]
Yes

**Comment by Ahanaf-Ether** [comment]
I think I mailed you

**Comment by Ahanaf-Ether** [comment]
![Uploading Screenshot_20211118-221833_Chrome.jpg…]()

**Comment by Ahanaf-Ether** [comment]
Here you go, in the tide prompt I just see "git Master"

**Comment by Ahanaf-Ether** [comment]
https://drive.google.com/file/d/1ILt6h8BJshIfkBrZrKMraihA97SiydQ-/view?usp=drivesdk

**Comment by Ahanaf-Ether** [comment]
I can't send the pic here for some weird reason

**Comment by IlanCosman** [comment]
Ok yah, I get what you're saying.

The current design is that SHAs are marked with an `@` before them, tags are marked with a `#` before them, and branches have no mark because that's the most common thing. You can't change this behavior.

The little "git" you are seeing before the branch name is in fact a single symbol, the git logo. 
It will show anywhere: branch, tag, or SHA.

I don't plan to change the behavior right now, it seems quite logical to me.

**Comment by Ahanaf-Ether** [comment]
ok i guess it makes sense, is there any way i emulate that in tide?

**Comment by Ahanaf-Ether** [comment]
Ok, I figured powerlevel 10k has the option at the end "git checkout" or something similar, should I make a pr with that option, or would I like to make an update so, we can that in tide?

**Comment by getsurenka** [comment]
is this https://imgur.com/a/ymDifQk normal ?

**Comment by IlanCosman** [comment]
Yes. That means you have four untracked files￼.
