### ISSUE TITLE
tide prompt hangs when the directory path is bigger than the available space

### ISSUE THREAD

**Issue by Jonathan-79** [IlanCosman/tide#25]
#### Describe the bug

When entering into a directory whose path is bigger than what the terminal can display in one line, tide prompt freezes and the terminal stops respoding

#### Steps to reproduce

1. mkdir -p /tmp/large/path/bigger/than/the/terminal/can/display/in/one/line
2. cd /tmp/large/path/bigger/than/the/terminal/can/display/in/one/line
3. tide and fish freezes

#### Screenshots

![github](https://user-images.githubusercontent.com/69280939/93133951-648e2100-f6ae-11ea-86c0-a8a274225573.png)

#### Environment (please complete the following information)

- Operating System: Manjaro
- Output of `tide bug-report`: 

```console
fish, version 3.1.2
tide, version 2.3.0
xterm-256color
```

**Comment by IlanCosman** [comment]
Thanks for the report @Jonathan-79 😄 This might be a tough one. The issue is not in fact having the prompt larger than the line. Fish is equipped to deal with this. We can demonstrate this easily by creating the same large directory in our `$HOME` directory.

1. Make console as small as possible
2. `mkdir -p ~/large/path/bigger/than/the/terminal/can/display/in/one/line/abcdefg`
3. `cd ~/large/path/bigger/than/the/terminal/can/display/in/one/line/abcdefg`
4. See `>` character and able to interact and run commands

If we create that same directory in `/tmp` we hang.

1. Make console as small as possible
2. `mkdir -p /tmp/large/path/bigger/than/the/terminal/can/display/in/one/line/abcdefg`
3. `cd /tmp`/large/path/bigger/than/the/terminal/can/display/in/one/line/abcdefg`
4. Hangs until you press `Ctrl+C`

There's something weirder going on in Tide's shortening algorithm. I'll poke around and see what I can do. Until then, just use big terminals I guess 😂

P.S. Your screenshot shows some [font issues](https://github.com/romkatv/powerlevel10k/#sub-pixel-imperfections-around-powerline-symbols) where the glyphs don't match up perfectly. You might want to change your font size up or down by one.

**Comment by Jonathan-79** [comment]
Hello @IlanCosman , thank you for the tips related to my font.

Indeed, the problem does not occur on all folders and it is not a real deal breaker
