### ISSUE TITLE
Adding context item to left prompt

### ISSUE THREAD

**Issue by Epse** [IlanCosman/tide#27]
This seems mostly like a docs issue, but I found in the configuration docs that there is a `context` item, which is exactly what I wanted. The wizard doesn't give me that option though, so I went hunting for where the config is actually stored (how to manually add things should really be documented and once I figure it out, I'll gladly make a docs patch) and found it in `fish_variables`.

So I changed `tide_left_prompt_items` from `pwd \x1egit_prompt\x1enewline\x1eprompt_char` to `context\x1epwd\x1egit_prompt\x1enewline\x1eprompt_char` and found no difference at all. As a test, I dropped the `pwd` part from the variable and immediately saw the change.

Am I missing something?

**Comment by IlanCosman** [comment]
Thanks for asking @Epse 😄 The context item by default displays only when in ssh or as the root user. The first variable under [context](https://github.com/IlanCosman/tide/blob/main/docs/Configuration.md#context) is `always_display`. Set `tide_context_always_display` to `true` to have `context`.

**Comment by Epse** [comment]
Oh that's actually behaviour I might want to keep! I clearly didn't scroll far enough, though a "default value" field in these tables might also be useful...

Might write a docs patch later, if that would be welcome?

**Comment by IlanCosman** [comment]
Originally, when Tide had just one style, the docs had a default value column. Now that Tide has 4 different styles, most variables have no consistent default across styles. That's why I suggest for people to look at the default configurations if they are interested in customizing beyond what the configuration wizard can do. I don't really see a reasonable way to add a default value field to those tables, but if you have any ideas, PRs are always welcome 😄
