### ISSUE TITLE
Prompt shows multiple lines when terminal shrinks horizontally

### ISSUE THREAD

**Issue by gusruben** [IlanCosman/tide#275]
#### Describe the bug

When the terminal shrinks horizontally, the prompt moves down a line, but it doesn't clear what was there, so there's still a layer of the prompt left behind.

#### Steps to reproduce

1. Shrink the terminal horizontally
2. See error

#### Screenshots

Prompt normally:
![image](https://user-images.githubusercontent.com/95830851/162447207-d59bcbd6-9d4c-49e1-8d17-db1f2e302256.png)

Prompt after the terminal is shrunk by one column:
![image](https://user-images.githubusercontent.com/95830851/162447330-3444dfcf-dfac-4520-a0e0-36a72bebb416.png)

#### Environment

Output of `tide bug-report`:

```text
fish version: 3.4.1
tide version: 5.2.0
term: xterm-kitty
os: Ubuntu 20.04
terminal emulator: Kitty
fish startup: 4.12 millis
fisher plugins: jorgebucaran/fisher
```

(I'm using the manual install, since the fisher version isn't updated to `5.20`.)

#### Additional context

The prompt in the screenshots is customized, but the default prompt has the same problem. there doesn't need to be a connector on the top, and this also applies to one-line prompts. This works for any terminal I have tested as well, and expanding the terminal works fine.

**Comment by gusruben** [comment]
This seems to work in Konsole, actually, but still doesn't work in other terminal emulators like hyper or st.

**Comment by IlanCosman** [comment]
Unfortunately this is just a general terminal-prompt bug thing. Powerlevel10k has the same problem https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

You can reproduce using extremely simple fish code:

```fish
function _refresh_prompt --on-variable COLUMNS
    commandline -f repaint
end

function fish_prompt
    string repeat --max $COLUMNS -
    echo $PWD
end
```

There really isn't a much better alternative though. If we don't have the `_refresh_prompt` function, we just get overflow because the first line is equal to terminal width, so decreasing it will always add a new line.

Nothing to be done here, sorry 😞
