### ISSUE TITLE
tests/_tide_item_time.test.fish fails with non-English locale

### ISSUE THREAD

**Issue by jose1711** [IlanCosman/tide#291]
#### Describe the bug

`_tide_item_time.test.fish` may fail if `LANG` is set to value other than `C.utf8`.

#### Steps to reproduce

1. Enable `sk_SK.utf8` locales and regenerate
2. Run `LANG=sk_SK.utf8 make test`
3. Get error

```
Testing file tests/_tide_item_time.test.fish ... Failure:

  The CHECK on line 14 wants:
    {{\\d\\d:\\d\\d:\\d\\d (A|P)M}}

  which failed to match line stdout:3:
     05:27:03 

  Context:
     17:27:03
     05:27:03  <= does not match CHECK '{{\\d\\d:\\d\\d:\\d\\d (A|P)M}}' on line 14

  when running command:
    fish tests/_tide_item_time.test.fish
```

4. Running `LANG=C.utf8 make test` removes the problem.

**Comment by halostatue** [comment]
This does not just affect non-English locales, but any locale or system setting where `%T` is a 24-hour clock. I use `en-CA.UTF-8`, but have set my system setting to use the 24 hour clock. (Interesting `strftime(3)` indicates that `%T` should be `%H:%M:%S`, which is the 24 hour clock, whereas it appears that sometimes it is `%I:%M:%S %p` (which is `%r`), but is still slightly different than the pattern, because `date +"%T -- %r"` gives me `00:05:35 -- 12:05:35 am`, so `am` instead of the pattern `(A|P)M`, unless the regex test is case-insensitive but not marked that way.

**Comment by IlanCosman** [comment]
Honestly, I know absolutely nothing about locales, languages etc. If anyone else wants to work on this, that would be greatly appreciated. Surely there must be _some_ way of getting a 24-hour time and a 12-hour time with am/pm marking regardless of the system.

**Comment by jose1711** [comment]
Maybe you can just pin the locale for the last test to `C.utf8`. That should be available on all systems.
```
# 12 Hour
LANG=C.utf8 _time %r # CHECK: {{\d\d:\d\d:\d\d (A|P)M}}
```

**Comment by IlanCosman** [comment]
@halostatue @jose1711

Does `date +"%I:%M:%S %p"` produce something like `01:59:00 PM`?
Does `date +"%H:%M:%S"` produce something like `13:59:20`?

This appears to be how p10k does it.

**Comment by halostatue** [comment]
```console
❯ date +"%I:%M%:%S %p"
08:56:35 pm
❯ date +"%H:%M:%S"
20:56:55
```

**Comment by halostatue** [comment]
It appears to do so on macOS:

```console
❯ LANG=sk_SK.utf8 date +"%I:%M:%S %p"
10:59:31 PM
❯ LANG=sk_SK.utf8 date +"%H:%M:%S"
22:59:41
```

**Comment by primeapple** [comment]
This is fixed in https://github.com/IlanCosman/tide/pull/381

Can be closed.
