### ISSUE TITLE
Operating system icon?

### ISSUE THREAD

**Issue by dannycallaghan** [IlanCosman/tide#350]
Hi

Sorry, I've read the documentation, and I can't see how to change my operating system icon - is that possible? I'm on a Mac, and I don't want to see the Apple icon 😄 

Thanks

**Comment by IlanCosman** [comment]
Oh, I suppose that should be in the docs. You're not really intended to change the icon though, since that kind of defeats the purpose 😄 

If you want to change the icon you'd run `set tide_os_icon <new_icon>`
If you want to remove the OS item, you'd run `_tide_find_and_remove os tide_left_prompt_items` and restart your terminal.

**Comment by dannycallaghan** [comment]
Thanks so much, that's awesome. 

Amazing product. And support, it turns out 😄
