### ISSUE TITLE
failed to execute process '/usr/bin/git': An argument or exported variable exceeds the OS argument length limit.

### ISSUE THREAD

**Issue by ashley0143** [IlanCosman/tide#372]
#### Describe the bug

getting  exec: Failed to execute process '/usr/bin/git': An argument or exported variable exceeds the OS argument length limit.
exec: Hint: Your exported variables take up over half the limit. Try erasing or unexporting variables.
exec: Failed to execute process '/usr/bin/git': An argument or exported variable exceeds the OS argument length limit.
exec: Hint: Your exported variables take up over half the limit. Try erasing or unexporting variables.

#### Steps to reproduce
just installed via the sh file

#### Screenshots
![image](https://user-images.githubusercontent.com/65588168/214311470-550a4bbc-1a62-4f3a-9b5d-cc18c92c4428.png)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.5.1
tide version: 5.5.1
term: xterm-256color
os: kubuntu 22.10
terminal emulator: Konsole
fish startup: 50.99 millis
fisher plugins: jorgebucaran/fisher
```

**Comment by faho** [comment]
Fish gives you a hint on what is wrong here:

> exec: Hint: Your exported variables take up over half the limit. Try erasing or unexporting variables.

What this means is that your exported variables are too large. UNIX has a limit on the arguments and environment variables that it accepts, and you've exceeded it.

What you want to do is to go through your exported variables and erase some. Since you can't execute any external commands, you need to do it with just fish builtins. Try something like

```fish
set -l minlen 2000
for var in (set -xn)
    set -l len (string length -- "$$var")
    test $len -gt $minlen; and echo -- $len $var
end
```

This will print all variables longer than 2000 characters, like "12424 foobar". You'll want to erase them - `set -e foobar` - until you no longer get the error.

The most likely cause here is that you have a universal variable that you append to in config.fish - we used to hit this with $fish_user_paths a bunch. You need to not do that, e.g. by checking if the component you want to add is already included:

```fish
# instead of
set fish_user_paths $fish_user_paths /my/path

# do
contains -- /my/path $fish_user_paths
or set fish_user_paths $fish_user_paths /my/path
```

(or for fish_user_paths specifically check [fish_add_path](https://fishshell.com/docs/current/cmds/fish_add_path.html))

**Comment by ashley0143** [comment]
thank you!
