### ISSUE TITLE
Git slow to appear

### ISSUE THREAD

**Issue by yanshay** [IlanCosman/tide#423]
Hi,

I've just installed fish and tide, and the git section of the prompt appears after some delay when I enter a folder with git. It is not immediate.
I also have Starship installed, and there I see no delay, the it's quicker when I put them to a 'race'. (so starship is done before the git section appears on tide)
I also saw on youtube a video on tide where it that doesn't appear slow like mine, and seems to appear immediately with the prompt, and not with such delay.
1. How should it work? Should the git section appear noticeably later?
2. If not, how can I troubleshoot this on my system?

**Comment by IlanCosman** [comment]
Really Tide is basically just running `git status --porcelain` in the background shell. So however long that takes is how long it should take for Tide to show the git item. 

Starship is written in a faster language, and does not use the CLI git tool (they use libgit2 I think). This means that Starship should be slightly faster in absolute terms. So indeed you would expect Starship overall to finish slightly before Tide refreshes the prompt. However, because Tide is async, your prompt is reactive during that waiting time, whereas with Starship you are blocked.

And this tradeoff of reactivity for total time is worth it, because the total time difference should be very small. Try comparing the runtime of `git status --porcelain` versus `starship prompt`. You can use `time`, or a more fancy tool like `hyperfine`.

Here's what I get in my Arch VM, in the massive llvm repo.

```shell
ilan@arch ~/llvm-project (main)> hyperfine --shell=fish "git status --porcelain" "starship prompt" -i
Benchmark 1: git status --porcelain
  Time (mean ± σ):     142.6 ms ±   3.6 ms    [User: 66.4 ms, System: 160.9 ms]
  Range (min … max):   138.8 ms … 150.4 ms    20 runs
 
Benchmark 2: starship prompt
  Time (mean ± σ):     145.5 ms ±   3.1 ms    [User: 71.2 ms, System: 168.5 ms]
  Range (min … max):   140.4 ms … 152.4 ms    20 runs
 
Summary
  git status --porcelain ran
    1.02 ± 0.03 times faster than starship prompt
```

So, with some Tide overhead, you can see that Starship will be slightly faster, but by a small amount.

---

All this is to say, no, your git section should not appear noticeably late unless you are entering a massive git repo, in which case Starship should also be slow.

**Comment by IlanCosman** [comment]
The difference is definitely variable depending on machine though. On my M1 Macbook Air, I get the following:

```shell
ilan@Ilans-Air ~/llvm-project (main)> hyperfine --shell=fish "git status --porcelain" "starship prompt" --warmup=20 --runs=20
Benchmark 1: git status --porcelain
  Time (mean ± σ):     655.3 ms ±  19.8 ms    [User: 135.4 ms, System: 2381.8 ms]
  Range (min … max):   633.7 ms … 686.4 ms    20 runs

Benchmark 2: starship prompt
  Time (mean ± σ):     511.0 ms ±   1.1 ms    [User: 105.2 ms, System: 2266.5 ms]
  Range (min … max):   508.9 ms … 513.0 ms    20 runs

Summary
  starship prompt ran
    1.28 ± 0.04 times faster than git status --porcelain
```

Which is a noticeable performance difference. Even so I think the user experience is better due to perceived latency.

**Comment by yanshay** [comment]
Running the tests you suggested shows even better results in favor of tide, however, see video below how tide git section of the prompt shows up later (not dramatic, but annoying to my eyes) than Starship.

```
Benchmark 1: git status --porcelain
  Time (mean ± σ):      12.1 ms ±   0.8 ms    [User: 4.7 ms, System: 5.6 ms]
  Range (min … max):    11.0 ms …  13.7 ms    20 runs

Benchmark 2: starship prompt
  Time (mean ± σ):      40.2 ms ±   2.0 ms    [User: 28.8 ms, System: 26.6 ms]
  Range (min … max):    36.7 ms …  43.3 ms    20 runs

Summary
  git status --porcelain ran
    3.33 ± 0.27 times faster than starship prompt
```

I use Zellij sync mode so what I type goes into both screens simultaneously and they are in sync:

https://github.com/IlanCosman/tide/assets/18171583/f38ed0db-a7b0-40cf-8452-4e12a928585f

**Comment by IlanCosman** [comment]
Yah the test you showed looks roughly like what I'd expect. Tide offers a worse experience than Starship for entering/exiting small git repos. While you're in the repo though, the experience is the same. And then for larger repos Tide becomes better for both entering/exiting and acting within the repo.

> BTW - I don't know to read the code, but looking at _tide_item_git.fish it seems there more than a single call to git, it seems to call git branch and git tag and git rev-parse, only then comes the git status.

This contributes to my statement above. The git branch, tag, etc. are constant time with respect to repo size. So for large repos, only the git status matters.

So yes, for small repos, Starship offers a nicer enter/exit experience. But usually when you enter a repo, you are going to spend some time there doing work, where Tide is equal. In larger git repos, Tide is significantly better.
