### ISSUE TITLE
Where is default configuration placed?

### ISSUE THREAD

**Issue by krzkaczor** [IlanCosman/tide#44]
Let me start by saying that I just started using fish so my question may be stupid. I enjoy using `tide`, I used configurator to come up with a nice prompt design but now I would like to tweak it a little bit more. 

Where is the configuration generated by the configurator placed? The only way I managed to access it is by listing all shell variables with (`set -S`). 

I would like to tweak it and put the whole configuration to `fish.config` so I can easily backup it etc.

**Comment by IlanCosman** [comment]
Hi Kris! This is indeed a common pain point for new fish users. Fish has a feature called [universal variables](https://fishshell.com/docs/current/index.html#more-on-universal-variables). Essentially it means that you can set a persistent variable from the commandline. Other shells do not have this feature, so one is forced to set the variable globally on every shell startup.

Fish's system is better in certain ways. You only need to set something once, and it doesn't have to be re-set every time slowing shell startup. However, universal variables can't really be backed up in the traditional sense. Instead you have to use an install script for your dotfiles that sets them once.

So here are your options:

`install_script.fish`:
```
set --universal foo bar
set --universal bar baz
```
and then on install `source install_script.fish`.

or `config.fish`:
```
set --global foo bar
set --global bar baz
```

So that's how you configure things in Fish. 

---

As for Tide specifically, here's my recommendation: Base your configuration in the `tide configure` wizard. The wizard already lets you do a large part of the customization that most people desire, and takes perhaps 10 seconds if you know the choices you want. 

Then in your install script/`config.fish` only change the variables you actually want to change. This will save you from having to backup your whole Tide configuration, which is over 100 variables, and also has the advantage that you can receive "updates" to the parts of your configuration you didn't customize.
