### ISSUE TITLE
Is Tide prompt stil in development?

### ISSUE THREAD

**Issue by bitconym** [IlanCosman/tide#543]
I see a lot of bugs reported, and the last commit was in February '24.

Also, I would like to know how to implement a custom theme (colorscheme) for the prompt parts, is there any standard way of doing this or do I need to override variables?

**Comment by IlanCosman** [comment]
I've been taking an extended break from Tide. I just haven't had the time / energy for a while, since I picked up other hobbies and then graduated from school and got a job. I think I might come back at some point, but no timeline on that.

I'm sorry to have sort of abandoned the project, but I do feel it's in a solid and highly usable place.

---

As for color scheme, you might or might not have to override variables, depending on what you want. 

You. can see what a full config looks like here: https://github.com/IlanCosman/tide/tree/main/functions/tide/configure/configs

If you want to use true-color (i.e. Tide doesn't care about what the terminal palette is), then yes, you have to override everything you want to change yourself. E.g. in this mode `tide_node_color` is `44883E`, a very specific and unique color of green, independent of any other green in the terminal or Tide colors.

If you want Tide to inherit from the terminal palette, then you can select that option in the configuration wizard, and then define the palette in your terminal. What this does is set things like `tide_node_color` to `green`. In which case it will be the same green as any other in your terminal / Tide colors.
