### ISSUE TITLE
Error "fish: Unknown command: _tide_item_git_prompt"

### ISSUE THREAD

**Issue by MrNanook** [IlanCosman/tide#89]
#### Describe the bug

After updating with `fisher update`, I'm getting the error "fish: Unknown command: _tide_item_git_prompt" (see more below).

#### Steps to reproduce

1. Start fish, or enter a command.

#### Expected behavior

Tide prompt without errors.

#### Environment (please complete the following information)

- Operating System: Manjaro Linux 20.2.1
- Output of `tide bug-report`: 

```console
fish, version 3.1.2
tide, version 4.0.0
xterm-256color
```

#### Additional context

Full error: 

```
fish: Unknown command: _tide_item_git_prompt
~/.config/fish/functions/_tide_left_prompt.fish (line 1): 
_tide_item_$item
^
in command substitution
        called on line 11 of file ~/.config/fish/functions/_tide_left_prompt.fish
in function '_tide_left_prompt'
        called on line 13 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
~/.config/fish/functions/_tide_left_prompt.fish: Unknown error while evaluating command substitution
in function '_tide_left_prompt'
        called on line 13 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
```

**Comment by IlanCosman** [comment]
Yah, that's from updating to v4. Probably should have warned people 😅 Just go through the configuration wizard again, or uninstall and reinstall Tide.

**Comment by MrNanook** [comment]
Yes, I tried removing/installing with `fisher`, but that didn't work (same error). `Config` also didn't work for same reason. Then I deleted files in /.config/fish/functions/ connected to tide, and reinstalled. That worked.

**Comment by jorgebucaran** [comment]
@IlanCosman Do you know how I can reproduce this? I don't understand why removing/installing or just updating with Fisher wouldn't do the trick. Maybe I'm missing something here.

**Comment by MrNanook** [comment]
I indeed updated with `fisher update` (added to first post).

**Comment by IlanCosman** [comment]
@jorgebucaran Sure. Clone Tide, checkout v3.2.0. Install Tide directory with fisher. Checkout v4.0.0, run `fisher update`. Should give you the same errors.

The problem is that I changed the name of an item from `git_prompt` to `git`. Updating won't change your `tide_left_prompt_items`, but uninstalling/reinstalling or going through the `tide configure` wizard absolutely should have. Not sure why it didn't work for you @MrNanook, my apologies for the inconvenience.

**Comment by jorgebucaran** [comment]
Makes sense, thank you, @MrNanook and @IlanCosman! 🙆‍♂️

**Comment by tatsy** [comment]
Hi, I came across with the same issue. I work on the same environment, namely
* Fish 3.1.2
* Tide 4.0.0
Also, My OS is MacOS Big Sur (and I didn't notice the problem when I am using Catalina). Is there any workaround other than direct install from the repo?

**Comment by IlanCosman** [comment]
> Is there any workaround other than direct install from the repo?

What do you mean by this? The solutions are as described above: Uninstall and then reinstall Tide, or go through the configuration wizard again.

**Comment by tatsy** [comment]
Hi @IlanCosman,

Thank you for your reply. I meant if there is another way to install a lower version because downloading the previous version through Git is rather tedious.

By the way, I finally found that `fisher` allow us to specify a tag to install. So, an easy way to downgrade to `v3.2.0` will be:

```
fisher remove IlanCosman/tide
fisher install IlanCosman/tide@v3.2.0
```
